from selenium.webdriver.common.by import By


class LeftMenuLocators:
    CATEGORIES_FOR_WOMAN = (By.CSS_SELECTOR, '#categories_block_left .title_block')
    BUTTON_TOP_KINDS = (By.CSS_SELECTOR, '#categories_block_left li span')
    NAME_FIELD_TOPS = (By.CSS_SELECTOR, '#categories_block_left li a')
    BUTTON_DRESSES_KINDS = (By.CSS_SELECTOR, '#categories_block_left li.last span')
    NAME_FIELD_DRESSES = (By.CSS_SELECTOR, '#categories_block_left li.last a')
    CATALOG_NAME = (By.CSS_SELECTOR, '#layered_block_left .title_block')
    CATEGORIES_NAME = (By.CSS_SELECTOR, '#layered_block_left span.layered_subtitle')
    NAME_TOPS_CATEGORIES = (By.CSS_SELECTOR, '#ul_layered_category_0 [for="layered_category_4"] a')
    CHECKBOX_TOPS_CATEGORIES = (By.CSS_SELECTOR, '#ul_layered_category_0 [name="layered_category_4"]')
    NAME_DRESSES_CATEGORIES = (By.CSS_SELECTOR, '##ul_layered_category_0 [for="layered_category_8"] a')
    CHECKBOX_DRESSES_CATEGORIES = (By.CSS_SELECTOR, '#ul_layered_category_0 [name="layered_category_8"]')
    NAME_SIZE = (By.CSS_SELECTOR, '.layered_filter:nth-child(2) .layered_subtitle')
    CHECKBOX_SIZE_S = (By.CSS_SELECTOR, '#uniform-layered_id_attribute_group_1')
    CHECKBOX_SIZE_M = (By.CSS_SELECTOR, '#uniform-layered_id_attribute_group_2')
    CHECKBOX_SIZE_L = (By.CSS_SELECTOR, '#uniform-layered_id_attribute_group_3')
    NAME_SIZE_S = (By.CSS_SELECTOR, '[for = "layered_id_attribute_group_1"] a')
    NAME_SIZE_M = (By.CSS_SELECTOR, '[for = "layered_id_attribute_group_2"] a')
    NAME_SIZE_L = (By.CSS_SELECTOR, '[for = "layered_id_attribute_group_3"] a')
    NAME_COLOUR = (By.CSS_SELECTOR, '.layered_filter:nth-child(3) .layered_subtitle')
    CHECKBOX_COLOUR_BEIGE = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(1) input')
    BEIGE_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(1) label')
    CHECKBOX_COLOUR_WHITE = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(2) input')
    WHITE_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(2) label')
    CHECKBOX_COLOUR_BLACK = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(3) input')
    BLACK_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(3) label')
    CHECKBOX_COLOUR_ORANGE = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(4) input')
    ORANGE_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(4) label')
    CHECKBOX_COLOUR_BLUE = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(5) input')
    BLUE_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(5) label')
    CHECKBOX_COLOUR_GREEN = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(6) input')
    GREEN_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(6) label')
    CHECKBOX_COLOUR_YELLOW = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(7) input')
    YELLOW_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(7) label')
    CHECKBOX_COLOUR_PINK = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(8) input')
    PINK_COLOUR = (By.CSS_SELECTOR, '#ul_layered_id_attribute_group_3 li:nth-child(8) label')
    NAME_COMPOSITIONS = (By.CSS_SELECTOR, '.layered_filter:nth-child(4) .layered_subtitle')
    COTTON_COMPOSITIONS = (By.CSS_SELECTOR, '#ul_layered_id_feature_5 li:nth-child(1) label')
    VISCOSE_COMPOSITIONS = (By.CSS_SELECTOR, '#ul_layered_id_feature_5 li:nth-child(2) label')
    POLYESTER_COMPOSITIONS = (By.CSS_SELECTOR, '#ul_layered_id_feature_5 li:nth-child(3) label')
    CHECKBOX_COTTON_COMPOSITIONS = (By.CSS_SELECTOR, '#ul_layered_id_feature_5 li:nth-child(1) .checker')
    CHECKBOX_VISCOSE_COMPOSITIONS = (By.CSS_SELECTOR, '#ul_layered_id_feature_5 li:nth-child(2) .checker')
    CHECKBOX_POLYESTER_COMPOSITIONS = (By.CSS_SELECTOR, '#ul_layered_id_feature_5 li:nth-child(3) .checker')
    NAME_STYLES = (By.CSS_SELECTOR, '.layered_filter:nth-child(5) .layered_subtitle')
    CASUAL_STYLE = (By.CSS_SELECTOR, '#ul_layered_id_feature_6 li:nth-child(1) label')
    GIRLY_STYLE = (By.CSS_SELECTOR, '#ul_layered_id_feature_6 li:nth-child(2) label')
    DRESSY_STYLE = (By.CSS_SELECTOR, '#ul_layered_id_feature_6 li:nth-child(3) label')
    CHECKBOX_CASUAL_STYLE = (By.CSS_SELECTOR, '#ul_layered_id_feature_6 li:nth-child(1) .checker')
    CHECKBOX_GIRLY_STYLE = (By.CSS_SELECTOR, '#ul_layered_id_feature_6 li:nth-child(2) .checker')
    CHECKBOX_DRESSY_STYLE = (By.CSS_SELECTOR, '#ul_layered_id_feature_6 li:nth-child(3) .checker')
    NAME_PROPERTIES = (By.CSS_SELECTOR, '.layered_filter:nth-child(6) .layered_subtitle')
    COLOURFUL_DRESS_PROPERTIES = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(1) label')
    MAXI_DRESS_PROPERTIES = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(2) label')
    MIDI_DRESS_PROPERTIES = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(3) label')
    SHORT_DRESS_PROPERTIES = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(4) label')
    SHORT_SLEEVE_PROPERTIES = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(5) label')
    CHECKBOX_COLOURFUL_DRESS = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(1) .checker')
    CHECKBOX_MAXI_DRESS_ = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(2) .checker')
    CHECKBOX_MIDI_DRESS = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(3) .checker')
    CHECKBOX_SHORT_DRESS = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(4) .checker')
    CHECKBOX_SHORT_SLEEVE = (By.CSS_SELECTOR, '#ul_layered_id_feature_7 li:nth-child(5) .checker')
    NAME_AVAILABILITY = (By.CSS_SELECTOR, '#ul_layered_quantity_0 div')
    FIELD_AVAILABILITY = (By.CSS_SELECTOR, '#ul_layered_quantity_0 label')
    CHECKBOX_AVAILABILITY = (By.CSS_SELECTOR, '#ul_layered_quantity_0 .checker')
    NAME_MANUFACTURER = (By.CSS_SELECTOR, '.layered_filter:nth-child(8) .layered_subtitle')
    FASHION_MANUFACTURER = (By.CSS_SELECTOR, '#ul_layered_manufacturer_0 .checker')
    MANUFACTURER_LABEL = (By.CSS_SELECTOR, '#ul_layered_manufacturer_0 label')
    NAME_CONDITION = (By.CSS_SELECTOR, '.layered_filter:nth-child(9) .layered_subtitle')
    CHECKBOX_CONDITION = (By.CSS_SELECTOR, '#uniform-layered_condition_new')
    CONDITION_LABEL = (By.CSS_SELECTOR, '[for = "layered_condition_new"]')
    NAME_PRICE = (By.CSS_SELECTOR, '.layered_price .layered_subtitle')
    RANGE_LABEL = (By.CSS_SELECTOR, '[for = "price"]')
    RANGE_VALUE = (By.CSS_SELECTOR, '#layered_price_range')
    RANGE_SLIDER = (By.CSS_SELECTOR, '')

    LABEL_INFORMATION = (By.CSS_SELECTOR, '#informations_block_left_1 a')
    DELIVERY_CATEGORY = (By.CSS_SELECTOR, '.list-block li:nth-child(1)')
    LEGAL_NOTICE_CATEGORY = (By.CSS_SELECTOR, '.list-block li:nth-child(2)')
    TERMS_AND_CONDITIONS_OF_USE_CATEGORY = (By.CSS_SELECTOR, '.list-block li:nth-child(3)')
    ABOUT_US_CATEGORY = (By.CSS_SELECTOR, '.list-block li:nth-child(4)')
    SECURE_PAYMENT_CATEGORY = (By.CSS_SELECTOR, '.list-block li:nth-child(5)')
    OUR_STORES_CATEGORY = (By.CSS_SELECTOR, '.list-block li:nth-child(6)')
    






